#!/usr/bin/env node
const convert = require("./convertFormat.js").convertToOldFormat;
const data = require("./jsrepository-master.json");

const result = convert(data);

require("fs").writeFileSync(
  "jsrepository.json",
  JSON.stringify(result, null, 2)
);
